### ISSUE TITLE
[BUG]: flashing and booting issues

### ISSUE THREAD

**Issue by sskorol** [jetsonhacks/bootFromExternalStorage#3]
**Describe the issue**

- Followed the steps from this video: https://www.jetsonhacks.com/2021/08/25/native-boot-for-jetson-xaviers/
- When I ran `flash_jetson_external_storage.sh` it failed with the following stacktrace:
```bash
[   0.5738 ] tegrasign_v3.py --key None --list bct_list.xml --pubkeyhash pub_key.key --getmontgomeryvalues montgomery.bin
[   0.5775 ] /usr/bin/env: Traceback (most recent call last):
  File "./tegraflash.py", line 1296, in <module>
    tegraflash_run_commands()
  File "./tegraflash.py", line 1155, in tegraflash_run_commands
    interpreter.onecmd(command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "./tegraflash.py", line 667, in do_sign
    tegraflash_sign(exports)
  File "/home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 1078, in tegraflash_sign
    tegraflash_generate_bct()
  File "/home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 4004, in tegraflash_generate_bct
    tegraflash_generate_br_bct(True)
  File "/home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 3510, in tegraflash_generate_br_bct
    run_command(command)
  File "/home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 202, in run_command
    log = print_process(process, enable_print)
  File "/home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 164, in print_process
    outputchar = output.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Error: /home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/bootloader/signed/flash.idx is not found
Error: failed to relocate images to /home/skorol/Projects/bootFromExternalStorage/R32.6.1/Linux_for_Tegra/tools/kernel_flash/images
Cleaning up...
```

**Which version of Ubuntu on the Host machine**
Ubuntu version: 20.04.2 LTS

**Which Jetson**
Jetson: Xavier NX

**To Reproduce**
Steps to reproduce the behavior: just run `flash_jetson_external_storage.sh` following the video guide

**Expected behavior**
Flashing should be completed.

**Comment by anhmiuhv** [comment]
The SD card thing is because of the boot order of the bootloader. If Your sd card is present and  not empty, the jetson xavier nx will priotize booting from the SD card.

**Comment by jetsonhacks** [comment]
Most of these issues have been addressed now.

**Comment by NickBeers** [comment]
I have tried this step by step a dozen times.  All the scripts seem to work, the flash ends in success.  If I try to screen into it, it auto fails.  If I try to putty from Windows, it asks for a localhost login and password.  Any idea what that could be?  I have tried from an Ubuntu 20.04 host, and then a fresh ubuntu 18.04 host.  I'm at a loss

**Comment by jetsonhacks** [comment]
@NickBeers Are you using a Xavier NX or AGX Xavier? Did you try to set it up with a monitor, keyboard and mouse?

**Comment by NickBeers** [comment]
I'm have an Xavier NX, with a SK Hynix 512 MB Gen 3x4 drive, no sd card.  It asks for the username/password from screen too, I just have to sudo screen to get to that part.  I'm trying to set this up headless, so maybe that is the problem.  After the flashing script exits, do I turn off the jetson?  I may be making a silly mistake between the end of the script and trying to screen or putty into it.  I'll try hooking it up to a monitor and keyboard this time, I've ran that script maybe 20 times.  

Thanks for your awesome videos, I enjoy the style of them greatly!

**Comment by NickBeers** [comment]
@jetsonhacks Just tried with a monitor, it shows the Nvidia logo, some text for a second, then goes blank.  Let me try another drive and see if maybe I have a defective drive.

**Comment by jetsonhacks** [comment]
> I'm have an Xavier NX, with a SK Hynix 512 MB Gen 3x4 drive, no sd card. It asks for the username/password from screen too, I just have to sudo screen to get to that part. I'm trying to set this up headless, so maybe that is the problem. After the flashing script exits, do I turn off the jetson? I may be making a silly mistake between the end of the script and trying to screen or putty into it. I'll try hooking it up to a monitor and keyboard this time, I've ran that script maybe 20 times.
> 
> Thanks for your awesome videos, I enjoy the style of them greatly!

Thank you for the kind words. Some people have reported issues with oem-config not coming up correctly. anhmiuhv is one of the NVIDIA engineers who works on this, this is reported in another issue:

Flash from external storage should already flash to emmc in the process. 

Oem-config is expected to run fine when booting from NVMe; but in case when flashing to NVMe and oem-config fails to start, you can run
```
sudo ./tools/l4t_create_default_user.sh -u ubuntu -p ubuntu # this command create username ubuntu and password ubuntu
```
to skip oem-config

You'll need to be in the Linux_for_Tegra directory when executing the above command. Note that you may have to expand your APP partition to fill up the rest of your disk. That's part of the config walk through process. I don't know yet if this is due to a change that they're making for adding this feature to the GUI SDK Manager, or some other issue. 

I know that people of AGX Xavier are experiencing this issue.

**Comment by NickBeers** [comment]
@jetsonhacks The new drive did the same thing.  I ran that command you just suggested directly after the flashing was complete without rebooting, and it made a user that allows me to log in.  Thank you very much!!!

**Comment by NickBeers** [comment]
@jetsonhacks Just ran into an issue, my root partition only allocated 14GB.  Any tips on extending it to fill the whole drive?

**Comment by jetsonhacks** [comment]
@NickBeers Open the Disks application, select the drive.
Go to Partition 1 (it's Filesystem, labeled APP)
Click the gear icon.
Select 'Resize..'

**Comment by jetsonhacks** [comment]
@NickBeers Did you flash from a PC running Ubuntu natively?

**Comment by NickBeers** [comment]
@jetsonhacks I did flash it from an Ubuntu 18.04 install.  Do you know how to do it headless?  I tried using gdisk, and couldn't figure out how to get the resize to stick.  I selected the /dev/nvme0n1, then resized partition 1, which is my App partition.  In gpart, it says it goes for 450GB, but when I quit and reboot it is still 14GB.

**Comment by anhmiuhv** [comment]
You also need to resize the file system itself in addition to resizing the partition.

sudo resize2fs /dev/nvme0n1p… ( the APP parition)

**Comment by anhmiuhv** [comment]
This step is done by oem config but because oem-config is skipped you have to do it yourself

**Comment by NickBeers** [comment]
@anhmiuhv That worked!  Thank you very much!!
